.TH GDM\-THEME 1 2021\-01\-07 "Script v1.0" "GDM Tools"
.SH NAME
gdm-theme \- a utility to set GDM theme and background
.SH SYNOPSIS
\fBgdm\-theme \-e\fR|\fB\-h\fR|\fB\-l\fR|\fB\-m\fR|\fB\-r\fR
.sp
\fBgdm\-theme examples\fR|\fBhelp\fR|\fBlist\fR|\fBmanual\fR|\fBreset\fR
.sp
\fBgdm\-theme \-s\fR|\fBset\fR \fB<\fItheme\fB>\fR [\fIimage\fR]
.sp
\fBgdm\-theme \-b\fR|\fBbackup \-u\fR|\fBupdate\fR|\fB\-r\fR|\fBrestore\fR
.sp
\fBgdm\-theme \-x\fR|\fBextract\fR [\fIlocation\fR]
.SH DESCRIPTION
List available theme options for Gnome Dislplay Manager (GDM), and set GDM theme and background image. A theme, to be a valid theme for this program, should be located in \fI/usr/share/themes/\fR and contain a subdirectory for \fIgnome-shell\fR. In simple words, a theme has to be a valid \fIgnome-shell\fR theme located in \fI/usr/share/themes\fR in order to be a valid GDM theme.
.
\fIgdm-theme(1)\fR has a smart backup system which backs up the default GDM theme (/usr/share/gnome-shell/gnome-shell-theme.gresource) because it needs to be overwritten in order for other themes to be applied to GDM. This backup is used when you set '\fIdefault\fR' theme using \fIgdm-theme(1)\fR. Smart backup means that \fIgdm-theme(1)\fR will replace the old backup with the new one if the default theme gets updated by the system. This is very useful in case Gnome gets a major version upgrade because the default theme of previous Gnome version mostly does not work well with a more recent version of Gnome. This introduces a little problem for \fIgdm-theme(1)\fR which is discussed in \fBWARNING\fR section.
.SH OPTIONS
.SS
\fB\-l\fR,\fBlist\fR
list available GDM themes. A theme has to be either the default \fIgnome-shell\fR theme or a valid \fIgnome-shell\fR theme stored in \fI/usr/share/themes\fR in order to show up in the list. A valid \fIgnome-shell\fR theme is a theme which has a subdirectory named \fIgnome-shell\fR with \fIgnome-shell.css\fR file present in it. This option will always show \fIdefault\fR theme as the first in the list.
.
.SS
\fB-s\fR,\fBset <\fItheme\fB> \fR[\fIimage\fR]
set \fB<\fItheme\fB>\fR as GDM theme and if provided [\fIimage\fR] as GDM background image, where \fB<\fItheme\fB>\fR is the name of the theme and [\fIimage\fR] is path to an image file.
.
Your choices for theme are '\fIdefault\fR', all system-wide gnome-shell themes, and \fI-b\fR or \fI--background\fR. Your choices for an image are /path/to/image and 'none'. You can also choose to omit the image part.
.
If you provide name of a theme, it will be set as GDM theme. If you type \fI-b\fR or \fI--background\fR instead of a theme name, you will be able to change GDM background without changing the theme. Similarly, if you provide a path to an image file, it will be used as GDM background, but if you do not provide anything as an image, you will be able to change GDM theme without changing the background image. If you type 'none' instead of path to an image file, GDM background image will be removed.
.sp
\fBExamples:\fR
.sp
\fBgdm\-theme set \fIYaru\-dark\fR
.RS
will set \fIYaru-dark\fR as GDM theme
.RE
.
\fBgdm\-theme \-s default \fI~/Pictures/Sunset.jpg\fR
.RS
will set \fIdefault\fR GDM theme with \fI~/Pictures/Sunset.jpg\fR as background
.RE
.
\fBgdm\-theme set \-b \fI~/Pictures/Cat.jpg\fR
.RS
will set \fI~/Pictures/Cat.jpg\fR as GDM background
.RE
.
\fBgdm\-theme -s \fIMateria \fBnone\fR
.RS
will set \fIMateria\fR as GDM theme with no background image
.RE
.
.SS
\fB\-r\fR,\fBreset\fR
reset everything to the way it was before the use of \fIgdm\-theme(1)\fR except for removing the backup it created. This option sets unmodified \fIdefault\fR GDM theme (\fI/usr/share/gnome-shell/gnome-shell-theme.gresource.default\fR) as GDM theme by moving it to its original place (\fI/usr/share/gnome-shell/gnome-shell-theme.gresource\fR), removes GDM background image file (/usr/share/gnome-shell/theme/gdm-background) which was created by \fIgdm\-theme(1)\fR, and sets \fIgdm-theme.gresource\fR name in \fIupdate-alternatives(1)\fR to auto.
.
.SS
\fB\-b\fR,\fBbackup \fR{\fIaction\fR}
update or restore backup of the default GDM theme. This additional backup can be very helpful if some other program or a bug in \fBgdm\-theme(1)\fR messes up the default GDM theme. This option requires at least one action. The action choices are \fBupdate\fR and \fBrestore\fR or their short forms \fB\-u\fR and \fB\-r\fR. For example,
.sp
\fBgdm\-theme \-b update\fR
.RS
will update backup to the newest version of default GDM theme
.RE
.
\fBgdm\-theme backup -r\fR
.RS
will restore default GDM theme from the backup
.RE
.
.SS
\fB\-x\fR,\fBextract\fR [\fIlocation\fR]
extract the \fIdefault\E GDM theme to specified \fIlocation\R if provided. If no \fIlocation\fR is provided, it is extracted to system-wide themes directory \fI/usr/share/themes\fR. This can be helpful when you use some \fIweird Gnome session\fR such as \fIubuntu-session\fR whose \fIdefault\fR gnome-shell theme is not the actual \fIdefault\fR gnome-shell theme provided by gnome. You cannot set \fIdefault\fR gnome-shell theme in \fIUbuntu\fR unless you install '\fIgnome-session\fR' and log in to \fIGnome (session)\fR instead of \fIUbuntu (session)\fR. With this option, you will be able to set gnome-shell theme to the actual \fIdefault\fR gnome-shell theme even when in \fIUbuntu (session)\fR. It will be presented as '\fIDefault-extracted\fR' in gnome-tweaks app.
.
.SS
\fB\-h\fR,\fB\-\-help\fR,\fBhelp\fR
print a short help message which provides program name, a short description of the program, and command options with a little description of each option too.
.
.SS
\fB\-m\fR,\fBmanual\fR
show this manual page
.
.SS
\fB\-e\fR,\fBexamples\fR
explain the usage of \fIgdm\-theme(1)\fR with examples.
.SH WARNING
GDM uses the file /usr/share/gnome\-shell/gnome\-shell\-theme.gresource as its theme. I am just going to call this file 'gresource file'. In order to set a theme as GDM theme, the \fIdefault\fR gresource file has to be replaced by the \fIcustom\fR theme's gresource file. The \fIdefault\fR gresource file has to be \fIbacked up\fR first if it is ever needed to be reused and it will surely be needed in future because user would want to set the default GDM theme at some point.
.sp
Other programs (that set and change GDM theme) \fIbackup\fR the \fIdefault\fR gresource file only on the first run if they \fIback\fR it \fIup\fR at all. When user sets \fIdefault\fR theme using any of those programs, they set that \fIbackup\fR as GDM theme. If Gnome gets upgraded, custom theme's gresource file is replaced with newer version of the \fIdefault\fR gresource file. Then you change GDM theme again to your preference. Since there is already a \fIbackup\fR present on the system, those programs do not \fIbackup\fR the newer version of \fIdefault\fR gresource file. Instead, they just replace it with a custom gresource file and keep using the old \fIbackup\fR as \fIdefault\fR theme. When a major version upgrade happens to Gnome, it breaks compatibility with older version of \fIdefault\fR theme. But those programs keep using the incompatible, old \fIbackup\fR of \fIdefault\fR theme(gresource file). In the end, their version of the default theme does not work correctly anymore.
.sp
To tackle the problem stated above, \fIgdm\-theme(1)\fR uses a dual backup system i.e it keeps two backups of the default gresource. One backup is managed automatically by \fIgdm\-theme(1)\fR (We will call it smart backup), and the other is created once on the first run and then managed manually with \fB-b\fR,\fBbackup\fR option of \fIgdm\-theme(1)\fR (We will call it manual backup. Whenever the word "backup" is used without specifying the type, manual backup is intended.
.sp
Smart backup is used as 'default' GDM theme in \fIgdm\-theme(1)\fR. \fIgdm\-theme(1)\fR marks the theme it sets with a \fIspecial file\fR i.e. it packs the special file inside gresource file of that theme. The special file is used to distinguish a custom theme's gresource file from the \fIdefault\fR gresource file. So, if currently set gresource file does not have that \fIspecial file\fR, it is understood to be the \fIdefault\fR gresource file. Whenever \fIgdm\-theme(1)\fR finds such a gresource file, it replaces the old \fIsmart backup\fR with that file. As a result, when \fIgdm\-theme(1)\fR runs after an upgrade to Gnome, \fI smart backup\fR gets upgraded too. Therefore, the \fIsmart backup\fR is always up-to-date.
.sp
This \fIsmart backup\fR comes with its \fBlimitations\fR though. Since the other programs do not mark the theme they set with \fIspecial identification file\fR like \fIgdm\-theme(1)\fR does, the file they replace default gresource with is recognized by \fIgdm\-theme(1)\fR as a newer version of the \fIdefault\fR gresource file. Hence, it replaces the \fIsmart backup\fR with that file and the theme set by other program is treated as the \fIdefault\fR theme. In this situation, the command '\fBgdm\-theme set \fIdefault\fR' will set that theme as GDM theme instead of the actual \fIdefault\fR GDM theme. Manual backup is present there to help in such situations.
.sp
To avoid this situation, you can opt to use only one program to set GDM theme instead of using multiple programs on the system. If you don't like the program you are currently using or want to check out some other program, then before using the new program, you should use the previous program to set the \fIdefault\fR GDM theme. The other thing you can do is to \fIbackup\fR the \fIdefault\fR gresource file by yourself before using any GDM theme changer. In this way, you will always have a \fIbackup\fR of the \fIdefault\fR GDM theme even if some program messes up its \fIbackup\fR. To do so, copy the default gresource file somewhere you won't accidently delete or forget. When some program messes up the \fIdefault\fR gresource file, you will just need to replace it with your own \fIbackup\fR. \fIgdm\-theme(1)\fR will automatically detect that as \fIdefault\fR gresource file and everything will be fine again.
.sp
In case you used some other program to set GDM theme, then installed and used \fIgdm\-theme(1)\fR to set GDM theme, now \fIgdm\-theme(1)\fR sets some other theme when you try to set the \fIdefault\fR GDM theme, the other program does not provide any way to set the \fIdefault\fR GDM theme, and you never \fIbacked up\fR the \fIdefault\fR GDM theme manually; You can solve this problem by \fIreinstalling\fR the package '\fIgnome\-shell\-common\fR' and then updating \fIgdm\-theme(1)\fR's backup by running '\fBgdm\-theme -b update\fR'. This will \fIfix everything\fR. In debian/ubuntu and derivatives, you can reinstall '\fIgnome\-shell\-common\fR' by running the command '\fBsudo apt reinstall \fIgnome\-shell\-common\fR'.
.sp
However, if you only use \fIgdm-theme(1)\fR for changing GDM theme or background, no such problem is supposed to occur.
.SH SEE ALSO
\fBgdm\-theme \fI\-\-help\fR
.sp
\fBgdm\-theme \fIexamples\fR
